"""Tests for Phase C — recon-signal-driven vuln-class user prompts.

`extract_intelligence_focus` reads the `intelligence_brief.md` produced
by Phase 1.5 and returns a class-specific markdown snippet. The pipeline
prefixes that snippet onto the Phase 2 user_prompt via
`build_vuln_user_prompt`. Tests verify the keyword-driven filtering,
the always-include-tech-signals fallback, and graceful no-brief behaviour.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from sentinel.agent.pentest.vuln_classes import VULN_CLASSES
from sentinel.agent.pentest.vuln_prompts import (
    build_vuln_user_prompt,
    extract_intelligence_focus,
)


_SAMPLE_BRIEF = """# Intelligence brief — https://example.com/

_Generated by Sentinel between recon and vuln-analysis. Read this BEFORE you form vuln hypotheses._

**Tech signals from recon:** graphql, react

## graphql

**Most likely vulns for this stack:**
- introspection enabled in prod
- depth-bombing DoS
- broken auth on mutations
- field-level authz bypass

**Recipe commands the recon agent should have run:**
- `curl -s -X POST {target}/graphql -H 'Content-Type: application/json' -d ...`

**Corpus hits:**
- some CVE here

## react

**Most likely vulns for this stack:**
- dangerouslySetInnerHTML reflected XSS
- JS bundle source maps leaking secrets

**Recipe commands the recon agent should have run:**
- `katana -u {target} -d 2 -jc -kf all`
"""


@pytest.fixture
def brief_path(tmp_path: Path) -> Path:
    p = tmp_path / "intelligence_brief.md"
    p.write_text(_SAMPLE_BRIEF)
    return p


def _vuln_class(slug: str):
    for c in VULN_CLASSES:
        if c.slug == slug:
            return c
    raise KeyError(slug)


def test_extract_returns_none_when_brief_missing(tmp_path: Path):
    out = extract_intelligence_focus(tmp_path / "nope.md", "xss")
    assert out is None


def test_extract_includes_tech_signals_line(brief_path: Path):
    out = extract_intelligence_focus(brief_path, "xss")
    assert "Tech signals from recon" in out
    assert "graphql" in out
    assert "react" in out


def test_extract_xss_picks_react_dangerouslyset(brief_path: Path):
    out = extract_intelligence_focus(brief_path, "xss")
    assert "react" in out.lower()
    assert "dangerouslySetInnerHTML" in out
    # Should NOT pull graphql bullets that don't mention xss keywords.
    assert "field-level authz bypass" not in out
    assert "depth-bombing" not in out


def test_extract_authz_picks_graphql_field_level(brief_path: Path):
    out = extract_intelligence_focus(brief_path, "authz")
    assert "field-level authz bypass" in out
    # The xss bullet shouldn't bleed into authz.
    assert "dangerouslySetInnerHTML" not in out


def test_extract_irrelevant_class_falls_back_to_tech_list(brief_path: Path):
    # No class keyword for "csrf" matches any bullet here, so we should
    # still get the tech-signals line + a "no class-specific bullets"
    # fallback note that names the detected stacks.
    out = extract_intelligence_focus(brief_path, "csrf")
    assert "Tech signals from recon" in out
    assert "csrf" in out.lower()
    assert "graphql" in out
    assert "react" in out


def test_extract_handles_empty_file(tmp_path: Path):
    p = tmp_path / "empty.md"
    p.write_text("")
    assert extract_intelligence_focus(p, "xss") is None


def test_build_user_prompt_no_brief_returns_base(tmp_path: Path):
    cls = _vuln_class("xss")
    prompt = build_vuln_user_prompt(
        cls, target="https://example.com", brief_path=tmp_path / "absent.md"
    )
    # No brief → no preamble.
    assert "Recon-derived focus" not in prompt
    assert "https://example.com" in prompt
    assert "Cross-Site Scripting" in prompt or "xss" in prompt.lower()


def test_build_user_prompt_with_brief_prefixes_focus(brief_path: Path):
    cls = _vuln_class("xss")
    prompt = build_vuln_user_prompt(
        cls, target="https://example.com", brief_path=brief_path
    )
    assert "Recon-derived focus" in prompt
    assert "dangerouslySetInnerHTML" in prompt
    # The base directive still appears after the focus block.
    assert "xss_analysis_deliverable.md" in prompt
    assert "xss_exploitation_queue.json" in prompt


def test_build_user_prompt_falls_back_when_brief_path_none():
    cls = _vuln_class("idor")
    prompt = build_vuln_user_prompt(
        cls, target="https://example.com", brief_path=None
    )
    assert "Recon-derived focus" not in prompt
    assert "idor_analysis_deliverable.md" in prompt
