"""Bundle evidence + extract scope-gated verification curls from an H1 report.

Two outputs per call:

  1. `<report-stem>.curls.sh` — runnable bash script with every `curl`
     command extracted from fenced ```bash / ```sh / ```http blocks
     in the report markdown. When `scope` is provided, each curl line
     is run through `scope.authorize_url(url)`; out-of-scope URLs are
     REPLACED with `# OUT-OF-SCOPE: <url> — dropped` so the script
     literally cannot execute a request against an unauthorized host.
     The authorize-or-deny decision is recorded by Scope.authorize_url
     itself in the engagement's `.audit-<id>.jsonl` (no extra
     bookkeeping in prepare).

  2. `<report-stem>-evidence.tar.gz` — gzipped tarball of every file
     under the report's sibling `evidence/` directory (if present).
     When no `evidence/` dir exists, the tarball path returned is None.

This is the "scope-gate at artifact generation" mitigation for
T-02-01-03 — an operator running the curls.sh after prepare() ran
cannot accidentally hit an out-of-scope host.
"""

from __future__ import annotations

import os
import re
import tarfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


# Recognized markdown fence headers (case-insensitive prefix) that may
# contain curl commands.
_FENCE_OPEN_RE = re.compile(
    r"^\s*```(bash|sh|shell|http)?\s*$",
    re.IGNORECASE,
)
_FENCE_ANY_RE = re.compile(r"^\s*```")

# URL extraction — first http(s) URL token after the `curl` verb.
_URL_RE = re.compile(r"https?://[^\s'\"`<>]+")


def _extract_curl_lines(text: str) -> list[str]:
    """Walk the report markdown line-by-line, return every line inside a
    bash/sh/shell/http fenced block that contains a `curl ` command.

    Continuation lines (lines starting with whitespace inside a curl
    block) are preserved alongside their curl parent.
    """
    out: list[str] = []
    in_fence = False
    fence_is_eligible = False
    for raw_line in text.splitlines():
        if _FENCE_ANY_RE.match(raw_line):
            if not in_fence:
                # Opening a fence — check if it's a shell-ish one we care about.
                m = _FENCE_OPEN_RE.match(raw_line)
                fence_is_eligible = bool(m)
                in_fence = True
            else:
                # Closing a fence.
                in_fence = False
                fence_is_eligible = False
            continue
        if not in_fence or not fence_is_eligible:
            continue
        # Collect curl lines + their continuations.
        stripped = raw_line.lstrip()
        if stripped.startswith("curl ") or stripped.startswith("curl\t"):
            out.append(raw_line)
        elif out and raw_line.startswith((" ", "\t")) and out[-1].rstrip().endswith("\\"):
            # Backslash continuation.
            out.append(raw_line)
    return out


def _extract_url(line: str) -> Optional[str]:
    """Return the first http(s) URL token from a curl line, or None when
    the line has no parseable URL (e.g. uses `$URL` env var)."""
    m = _URL_RE.search(line)
    return m.group(0) if m else None


def _build_script_header(report_path: Path, scope) -> str:
    """The auto-generated bash script's header (shebang + provenance +
    scope-gate banner)."""
    iso_now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        "#!/usr/bin/env bash",
        f"# Auto-generated by `sentinel h1 prepare` on {iso_now}",
        f"# Source: {report_path}",
    ]
    if scope is not None:
        eng = getattr(scope, "engagement_id", "<unknown-engagement>")
        lines.append(
            f"# SCOPE-GATED: each curl in this script was run through "
            f"Scope.authorize_url()"
        )
        lines.append(
            f"#   against engagement {eng}. Out-of-scope lines were "
            f"dropped (see"
        )
        lines.append("#   `# OUT-OF-SCOPE:` comments below).")
    else:
        lines.append(
            "# SCOPE-GATED: not performed — prepare() was called without "
            "a Scope."
        )
        lines.append(
            "#   Operator MUST eyeball every URL before running."
        )
    lines.append("# Do NOT run against out-of-scope hosts.")
    lines.append("set -euo pipefail")
    lines.append("")
    return "\n".join(lines)


def _bundle_evidence(report_path: Path, output_dir: Path) -> Optional[Path]:
    """If a sibling `evidence/` dir exists, gzip-tar it next to the
    report and return the tarball path. Otherwise return None."""
    ev_dir = report_path.parent / "evidence"
    if not ev_dir.is_dir():
        return None
    tarball = output_dir / f"{report_path.stem}-evidence.tar.gz"
    with tarfile.open(tarball, "w:gz") as tar:
        tar.add(ev_dir, arcname="evidence")
    return tarball


def prepare(
    report_path: Path | str,
    *,
    scope=None,
    output_dir: Path | str | None = None,
) -> tuple[Path, Optional[Path]]:
    """Extract verification curls + bundle evidence.

    Args:
      report_path: path to the H1 report markdown.
      scope: optional `sentinel.core.scope.Scope` instance. When
        provided, every extracted curl URL is run through
        `scope.authorize_url(url)`; OutOfScopeError → line replaced
        with `# OUT-OF-SCOPE: <url> — dropped`. When None, every curl
        line is emitted as-is and a "scope-gate NOT performed" warning
        appears in the script header.
      output_dir: where to write `<stem>.curls.sh` and
        `<stem>-evidence.tar.gz`. Defaults to the report's parent dir.

    Returns:
      `(curls_path, tarball_path_or_None)`.
    """
    report_path = Path(report_path)
    output_dir = Path(output_dir) if output_dir else report_path.parent
    output_dir.mkdir(parents=True, exist_ok=True)

    try:
        text = report_path.read_text(errors="replace")
    except OSError:
        text = ""

    curl_lines = _extract_curl_lines(text)

    # Apply the scope gate, producing the final list of output lines for
    # the runnable script.
    from sentinel.core.scope import OutOfScopeError

    out_lines: list[str] = [_build_script_header(report_path, scope)]
    n_dropped = 0
    for line in curl_lines:
        url = _extract_url(line)
        leading_ws = line[: len(line) - len(line.lstrip())]
        if url is None:
            # Unparseable URL — emit a warning comment but keep the line
            # so the operator can decide.
            out_lines.append(
                f"{leading_ws}# UNRESOLVED-URL — prepare() could not parse "
                f"a URL from this line; operator MUST manually scope-check "
                f"before running"
            )
            out_lines.append(line)
            continue
        if scope is not None:
            try:
                scope.authorize_url(url)
            except OutOfScopeError:
                out_lines.append(
                    f"{leading_ws}# OUT-OF-SCOPE: {url} — dropped"
                )
                n_dropped += 1
                continue
        out_lines.append(line)

    curls_path = output_dir / f"{report_path.stem}.curls.sh"
    curls_path.write_text("\n".join(out_lines) + "\n")
    # chmod +x so the operator can run it directly.
    try:
        curls_path.chmod(0o755)
    except OSError:
        pass

    tarball_path = _bundle_evidence(report_path, output_dir)

    # Stash the drop count on the curls_path object via attribute is
    # fragile; instead callers that need the count can re-grep the file.
    # (CLI _do_h1 prints the count by parsing curls.sh for the comment.)
    return curls_path, tarball_path
