"""POC-03 — Render a Finding + its poc_steps into the H1-narrative Markdown block.

The output of `render_poc_section(finding) -> str` is what the operator pastes
into HackerOne's "Proof of Concept" textbox. The heading hierarchy mirrors
his actual H1 reports under
`workspaces/2026-XX-XX-ExampleStore-bbp/deliverables/h1-submissions/` — NOT
the four-field H1 form template (he writes narrative submissions, not
form-field fills).

Contract (frozen by Plan 04-02; pinned by tests/test_poc_markdown.py):

    # Proof of Concept

    ## Title
    {finding.title}

    ## Description
    {finding.description, or auto-generated when empty}

    ### Reproduction
    #### Probe 1 — {step.description}
    ```{lang}
    {step.command}
    ```
    **Expected:**
    ```
    {step.expected_output or "(no output captured)"}
    ```
    ![Screenshot]({step.screenshot_path})        <-- only when set

    ### Combined Single-URL Attack       (optional)
    ### Affected Storefronts             (optional)
    ### Supporting Material/References   (optional)
    ### IP Address                       (optional)
    ### Timestamp                        (optional)

    ## Impact
    ...

    ## Attachments
    ...

    ## Additional information           (optional)

Intentionally NOT autogenerated:
  * `## Mitigation` — the operator writes mitigation inline in Impact when relevant
  * `## Summary` — the Title + Description sections cover that ground

Hermetic: no network, no subprocess, no LLM. Test 24 monkey-patches
urllib.request.urlopen to raise; render still succeeds.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from sentinel.core.findings import Finding


# ---------------------------------------------------------------------------
# Language-tag inference for fenced code blocks
# ---------------------------------------------------------------------------


_LANGUAGE_TAGS: dict[str, str] = {
    "curl": "bash",
    "wget": "bash",
    "http": "bash",       # httpie
    "python": "python",
    "python3": "python",
    "playwright": "python",
    "sqlmap": "bash",
    "bash": "bash",
    "sh": "bash",
}


_FIRST_TOKEN_RE = re.compile(r"\s*(\S+)")


def _infer_language_tag(command: str) -> str:
    """Map the FIRST whitespace token of a command to a fenced-code language.

    Defaults to ``bash`` for unknown tokens — operators can edit the
    fence by hand if they prefer a different language.
    """
    if not command:
        return "bash"
    m = _FIRST_TOKEN_RE.match(command)
    if not m:
        return "bash"
    token = m.group(1).lower()
    return _LANGUAGE_TAGS.get(token, "bash")


# ---------------------------------------------------------------------------
# Section helpers
# ---------------------------------------------------------------------------


def _render_title(finding: "Finding") -> str:
    return f"## Title\n\n{finding.title}"


def _autogenerate_description_body(finding: "Finding") -> str:
    """When finding.description is empty/whitespace-only, build a one-paragraph summary.

    Format: ``This finding affects {target}{location_suffix}. Severity: {SEVERITY}.{cwe_suffix}``
    """
    location_suffix = f" (location: {finding.location})" if finding.location else ""
    cwe_suffix = f" Weakness class: {finding.cwe}." if finding.cwe else ""
    severity_str = finding.severity.value.upper()
    return (
        f"This finding affects {finding.target}{location_suffix}. "
        f"Severity: {severity_str}.{cwe_suffix}"
    )


def _render_probe(step) -> str:
    """Render one PocStep as the `#### Probe N — desc` block.

    Layout (consumed verbatim by Test 7, Test 8, Test 9, Test 10, Test 11,
    Test 12):

        #### Probe {N} — {description}

        ```{lang}
        {command}
        ```

        **Expected:**

        ```
        {expected_output or "(no output captured)"}
        ```

        ![Screenshot]({screenshot_path})       <-- only when set
    """
    lang = _infer_language_tag(step.command)
    expected_body = step.expected_output if step.expected_output else "(no output captured)"
    parts = [
        f"#### Probe {step.step_number} — {step.description}",
        "",
        f"```{lang}",
        step.command,
        "```",
        "",
        "**Expected:**",
        "",
        "```",
        expected_body,
        "```",
    ]
    if step.screenshot_path:
        parts.extend(["", f"![Screenshot]({step.screenshot_path})"])
    return "\n".join(parts)


_FALLBACK_REPRO_BODY = (
    "No automated reproduction available — manual investigation required.\n"
    "This finding was emitted without a verified PoC bundle "
    "(verify-phase-03 may have been skipped)."
)


def _render_reproduction_block(finding: "Finding") -> str:
    """Render `### Reproduction` + body.

    Empty poc_steps -> the explicit fallback message (so the operator
    notices that nothing was captured). Otherwise: heading + one Probe
    block per step joined by blank lines.
    """
    if not finding.poc_steps:
        return f"### Reproduction\n\n{_FALLBACK_REPRO_BODY}"
    probes = [_render_probe(step) for step in finding.poc_steps]
    return "### Reproduction\n\n" + "\n\n".join(probes)


def _render_optional_subsections(finding: "Finding") -> list[str]:
    """Return the list of optional `### Xxx` blocks present on this finding.

    Each block is rendered ONLY when the corresponding finding data is
    populated. Order matches the operator's reference H1 report:

        ### Combined Single-URL Attack
        ### Affected Storefronts
        ### Supporting Material/References
        ### IP Address
        ### Timestamp
    """
    raw = finding.raw if isinstance(finding.raw, dict) else {}
    out: list[str] = []

    combined = raw.get("combined_attack_url")
    if combined:
        out.append(f"### Combined Single-URL Attack\n\n{combined}")

    storefronts = raw.get("affected_storefronts")
    if isinstance(storefronts, list) and storefronts:
        bullets = "\n".join(f"- {s}" for s in storefronts)
        out.append(f"### Affected Storefronts\n\n{bullets}")

    if finding.references:
        bullets = "\n".join(f"- {ref}" for ref in finding.references)
        out.append(f"### Supporting Material/References\n\n{bullets}")

    source_ip = raw.get("source_ip")
    if source_ip:
        out.append(f"### IP Address\n\n{source_ip}")

    timestamps = raw.get("probe_timestamps")
    if timestamps:
        out.append(f"### Timestamp\n\n{timestamps}")

    return out


def _render_description(finding: "Finding") -> str:
    """Render `## Description` + body + nested `### Reproduction` + optional sub-sections."""
    body = (
        finding.description
        if finding.description and finding.description.strip()
        else _autogenerate_description_body(finding)
    )
    parts = [
        "## Description",
        "",
        body,
        "",
        _render_reproduction_block(finding),
    ]
    rendered = "\n".join(parts)
    optional = _render_optional_subsections(finding)
    if optional:
        rendered = rendered + "\n\n" + "\n\n".join(optional)
    return rendered


def _render_impact(finding: "Finding") -> str:
    """Render `## Impact` + impact body + severity-tagged line + optional CWE line."""
    if finding.impact and finding.impact.strip():
        impact_body = finding.impact
    elif finding.description and finding.description.strip():
        impact_body = finding.description
    else:
        impact_body = "Manual review required — see Description above."

    severity_str = finding.severity.value.upper()
    severity_line = (
        f"This finding is rated **{severity_str}** based on Sentinel's triage."
    )
    parts = ["## Impact", "", impact_body, "", severity_line]
    if finding.cwe:
        parts.extend(["", f"**CWE:** {finding.cwe}."])
    return "\n".join(parts)


def _render_attachments(finding: "Finding") -> str:
    """Render `## Attachments` + deduped screenshot bullets or `No attachments.`."""
    paths = [
        step.screenshot_path for step in finding.poc_steps if step.screenshot_path
    ]
    deduped = list(dict.fromkeys(paths))   # preserves first-seen order
    if not deduped:
        return "## Attachments\n\nNo attachments."
    bullets = "\n".join(f"- {p}" for p in deduped)
    return f"## Attachments\n\n{bullets}"


def _render_additional_info(finding: "Finding") -> str:
    """Render `## Additional information` from raw['additional_info'] (if set)."""
    raw = finding.raw if isinstance(finding.raw, dict) else {}
    info = raw.get("additional_info")
    if not info:
        return ""
    return f"## Additional information\n\n{info}"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def render_poc_section(finding: "Finding") -> str:
    """Render the H1-narrative-aligned Markdown block for a Finding.

    Output structure matches the operator's actual H1 reports under
    workspaces/2026-XX-XX-ExampleStore-bbp/deliverables/h1-submissions/ —
    NOT the H1 form-field template.

    The returned string is what the operator pastes into HackerOne. No mitigation
    autogeneration (operators add mitigation context inline if needed).
    """
    sections = [
        "# Proof of Concept",
        _render_title(finding),
        _render_description(finding),
        _render_impact(finding),
        _render_attachments(finding),
    ]
    additional = _render_additional_info(finding)
    if additional:
        sections.append(additional)
    return "\n\n".join(s for s in sections if s).rstrip() + "\n"


__all__ = ["render_poc_section"]
